@startuml Municipios
skinparam classAttributeIconSize 0
class Municipio
{
    -nombre : string
    -provincia : string
    -comunidadAutonoma : string
}
class Inmueble
{
    -codigoReferencia : string[]
    -descripcion : string
    -precioVentas : int
}
class Casas
{
    -numHabitaciones : int 
    -metrosCuadrados : int
    -otrasCatacteristicas : string

}
class Locales
{

}
class Garaje
{

}
@enduml