@startuml VentaOnline
skinparam classAttributeIconSize 0
class Usuario
{
    -nombre : string 
    -id : int
    -direccion : string
    -telefono : int
    -correo : string
}
class Cliente
{
    -numCarros : int
    -numPedidos : int
    -pedido : Pedidos
    -infoCarro : CarroCompras
    +AñadirProductoCarro() : void
    +EliminarProductoCarro() : void
    +Comprar()
}
class Administradores
{
    
    +ModificarProducto() : void
    +CrearProducto() : void
    +BorrarProducto() : void
}
class CarroCompras
{
    -producto : Productos
}
class Pedidos
{
    -numPedido : int
    -InfoEnvio : string
    -producto : Productos
}
class Productos
{
    -precio : int 
    -cantidades : int 
}

Usuario <|--Cliente
Usuario <|--Administradores
Cliente *-- Pedidos 
Pedidos *-- Productos
Cliente *-- CarroCompras
CarroCompras *-- Productos
@enduml